#!/usr/bin/env bash

xmodmap -e 'clear Lock'
xmodmap -e 'keycode 66 = Hyper_L'
xmodmap -e 'add mod3 = Hyper_R'
xmodmap -e 'clear Mod4'
xmodmap -e 'add Mod3 = Hyper_L'
xmodmap -e 'add Mod4 = Super_L Hyper_R'

feh --randomize --bg-fill ~/.wallpaper/
